from typing import Dict, List
from datetime import datetime


class MatchExplainer:
    """
    DISABLED: This class previously used static rule-based explanations.
    Now all explanations (reasoning, strengths, concerns, campaign_fit) are generated by LLM.
    This class now acts as a pass-through to use LLM-generated explanations directly.
    """
    def __init__(self):
        pass

    def explain_match(
        self,
        creator: Dict,
        brand: Dict,
        scores: Dict[str, float],
        llm_reasoning: str = "",
        llm_strengths: List[str] = None,
        llm_concerns: List[str] = None,
        llm_campaign_fit: str = ""
    ) -> Dict[str, any]:
        """
        Use LLM-generated explanations directly instead of static rules.
        All explanations come from LLM analysis.
        """
        # Use LLM-generated explanations directly
        return {
            "reasoning": llm_reasoning if llm_reasoning else "No reasoning provided",
            "strengths": llm_strengths if llm_strengths else [],
            "concerns": llm_concerns if llm_concerns else [],
            "campaign_fit": llm_campaign_fit if llm_campaign_fit else "Unable to assess campaign fit"
        }
    
    # DISABLED: The following methods used static rule-based logic
    # They are kept for reference but unused - all explanations now come from LLM
    
    # def generate_strengths(...) - REMOVED: Now uses LLM-generated strengths
    # def generate_concerns(...) - REMOVED: Now uses LLM-generated concerns  
    # def generate_campaign_fit(...) - REMOVED: Now uses LLM-generated campaign_fit
    # def generate_reasoning(...) - REMOVED: Now uses LLM-generated reasoning directly

